# baseURL = "https://yjozen.github.io/myHugoSite/"
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
publishDir = "docs"
relativeURLs = true

[params]
  author = "Your Name"
  description = "A description of your site"
